version: '3.3'
services:
    bot:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - '6379:6379' 
    worker:
        build:
          context: .
          dockerfile: Dockerfile2
    